[ { name: 'Brother_DCP_7055W',
    isDefault: true,
    options: 
     { copies: '1',
       'device-uri': 'dnssd://Brother%20DCP-7055W._pdl-datastream._tcp.local./?bidi',
       finishings: '3',
       'job-cancel-after': '10800',
       'job-hold-until': 'no-hold',
       'job-priority': '50',
       'job-sheets': 'none,none',
       'marker-change-time': Sat Feb 14 2015 01:28:19 GMT+0100 (CET),
       'marker-colors': '#000000',
       'marker-levels': '-1',
       'marker-names': 'Black',
       'marker-types': 'toner',
       'number-up': '1',
       'printer-commands': 'ReportLevels,PrintSelfTestPage,PJLBidirectional,PJLWrite,PJLRead',
       'printer-info': 'Brother DCP-7055W',
       'printer-is-accepting-jobs': 'true',
       'printer-is-shared': 'false',
       'printer-location': '',
       'printer-make-and-model': 'Brother DCP-7055W CUPS',
       'printer-state': '3',
       'printer-state-change-time': Tue Jun 16 2015 23:48:26 GMT+0200 (CEST),
       'printer-state-reasons': 'toner-empty-report,com.brother.marker-supply-empty-warning',
       'printer-type': '77631556',
       'printer-uri-supported': 'ipp://localhost/printers/Brother_DCP_7055W' },
    status: 'IDLE' },
  { name: 'Photosmart_Plus_B210_series__7E028C_',
    isDefault: false,
    options: 
     { copies: '1',
       'device-uri': 'dnssd://Photosmart%20Plus%20B210%20series%20%5B7E028C%5D._ipp._tcp.local.',
       finishings: '3',
       'job-cancel-after': '10800',
       'job-hold-until': 'no-hold',
       'job-priority': '50',
       'job-sheets': 'none,none',
       'marker-change-time': Thu Mar 06 2014 18:24:18 GMT+0100 (CET),
       'marker-colors': '#000000,#00FFFF,#FF00FF,#FFFF00',
       'marker-high-levels': '100,100,100,100',
       'marker-levels': '30,100,60,70',
       'marker-low-levels': '0,0,0,0',
       'marker-names': 'black\\ ink,cyan\\ ink,magenta\\ ink,yellow\\ ink',
       'marker-types': 'inkCartridge,inkCartridge,inkCartridge,inkCartridge',
       'number-up': '1',
       'printer-commands': 'none',
       'printer-info': 'Imprimante HP B210',
       'printer-is-accepting-jobs': 'true',
       'printer-is-shared': 'false',
       'printer-location': 'Cuisine en haut',
       'printer-make-and-model': 'HP Photosmart Plus B210 series-AirPrint',
       'printer-state': '3',
       'printer-state-change-time': Thu Mar 06 2014 18:24:36 GMT+0100 (CET),
       'printer-state-reasons': 'offline-report',
       'printer-type': '69210124',
       'printer-uri-supported': 'ipp://localhost/printers/Photosmart_Plus_B210_series__7E028C_' },
    status: 'IDLE' },
  { name: 'Simulated_Color_Laser___MacBook_Pro_de_Sami',
    isDefault: false,
    options: 
     { copies: '1',
       'device-uri': 'dnssd://Simulated%20Color%20Laser%20%40%20MacBook%20Pro%20de%20Sami._ipps._tcp.local./?uuid=4ae18d2e-7bae-31dd-4dbd-84eb3d8d524e',
       finishings: '3',
       'job-cancel-after': '10800',
       'job-hold-until': 'no-hold',
       'job-priority': '50',
       'job-sheets': 'none,none',
       'marker-change-time': Thu Jan 01 1970 01:00:00 GMT+0100 (CET),
       'number-up': '1',
       'printer-commands': 'none',
       'printer-info': 'Simulated Color Laser @ MacBook Pro de Sami',
       'printer-is-accepting-jobs': 'true',
       'printer-is-shared': 'false',
       'printer-location': 'MacBook Pro de Sami',
       'printer-make-and-model': 'Simulated Color Laser-AirPrint',
       'printer-state': '3',
       'printer-state-change-time': Sun Jan 17 2016 17:40:34 GMT+0100 (CET),
       'printer-state-reasons': 'none',
       'printer-type': '2143484',
       'printer-uri-supported': 'ipp://localhost/printers/Simulated_Color_Laser___MacBook_Pro_de_Sami' },
    status: 'IDLE' } ]